// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwXVracoSSLPLclKzBtDlHu-WcDzShn0',
    appId: '1:1054626111652:web:019c987eaf186977b78631',
    messagingSenderId: '1054626111652',
    projectId: 'shopapp-34593',
    authDomain: 'shopapp-34593.firebaseapp.com',
    storageBucket: 'shopapp-34593.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2iSyTJPnnY_lkXoQLl1OFFuxy6j-vEjk',
    appId: '1:1054626111652:android:2852cd85c1874f59b78631',
    messagingSenderId: '1054626111652',
    projectId: 'shopapp-34593',
    storageBucket: 'shopapp-34593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAomlYx4Y1JMPNy5T9U8MhRNnjH275GrGQ',
    appId: '1:1054626111652:ios:d07b4f13baec2bd4b78631',
    messagingSenderId: '1054626111652',
    projectId: 'shopapp-34593',
    storageBucket: 'shopapp-34593.firebasestorage.app',
    iosBundleId: 'com.example.poketstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAomlYx4Y1JMPNy5T9U8MhRNnjH275GrGQ',
    appId: '1:1054626111652:ios:d07b4f13baec2bd4b78631',
    messagingSenderId: '1054626111652',
    projectId: 'shopapp-34593',
    storageBucket: 'shopapp-34593.firebasestorage.app',
    iosBundleId: 'com.example.poketstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMwXVracoSSLPLclKzBtDlHu-WcDzShn0',
    appId: '1:1054626111652:web:c4a9afc4f1d05964b78631',
    messagingSenderId: '1054626111652',
    projectId: 'shopapp-34593',
    authDomain: 'shopapp-34593.firebaseapp.com',
    storageBucket: 'shopapp-34593.firebasestorage.app',
  );
}
